spring:
  application:
    name: railsimserver
  task:
    scheduling:
      pool:
        size: 5
  jackson:
    serialization:
      INDENT_OUTPUT: true
    mapper:
      default-view-inclusion: true
  datasource:
    url: jdbc:postgresql://rk1-b:5432/railsim
    username: railsim
    password: railsim
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8083
