spring:
  main:
    web-application-type: none
  kafka:
    consumer:
      bootstrap-servers: cluster-1:9092,cluster-2:9092,cluster-3:9092
      auto-offset-reset: earliest # Either earliest, latest or none.
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: uk.co.raphel.railsim
    producer:
      bootstrap-servers: cluster-1:9092,cluster-2:9092,cluster-3:9092
      acks: -1 # Either 0,1 or -1. -1 waits for all replicas to acknowledge
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: jdbc:postgresql://192.168.1.119:5432/railsim
    username: railsim
    password: railsim
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083